ImageObjectFunctorial/CoimageObjectFunctorial
homalg-project/CategoryConstructor pull request #37
Opened 2022-03-25 16:36 UTC by mohamed-barakat

2022-03-25 17:17 UTC, zickgraf commented
Some thoughts: CAP seems to be inconsistent with its naming convention: `ImageObject` vs. `Coimage`. Maybe because `Image` is already occupied by GAP? But then again, `Cokernel` is not occupied by GAP but the object is still called `CokernelObject`. In any case, I think the names `ImageObjectFunctorial` and `KernelObjectFunctorial` are a bit weird, because the whole construction is functorial, not the object itself. Should we call it `ImageFunctorial`, and maybe at some point rename `KernelObjectFunctorial` to `KernelFunctorial`?

Ping @sebastianpos

2022-03-26 07:31 UTC, sebastianpos commented
Yes, it should be `CoimageObject` instead of `Coimage`. This is an old inconsistency.

I can explain my reasoning when it comes to the naming `KernelObjectFunctorial` (instead of `KernelFunctorial`):
In a truly categorical programming language, all data types X should be (1)-categories, and all functions f:X->Y between data types should be functors. In particular, f should be applicable both to objects and morphisms of the data type (=category) X.

Since GAP is not a categorical programming language, we need an extra function for the action of f on morphisms. My thought was that such functions should be called `fFunctorial`.

In particular, `KernelObject`, `KernelEmbedding`, `KernelLift` could all be extended to functors, i.e., not only `KernelObjectFunctorial` makes sense, but also `KernelEmbeddingFunctorial` and `KernelLiftFunctorial`.

Since this idea did not turn out as important as I thought in the beginning, I'm open to a change.

2022-03-26 10:28 UTC, mohamed-barakat commented
Maybe Sebastian's overall functoriality might become relevant in the future. For this, I would prefer `CoimageObjectFunctorial`. Shall I wait for `CAP` to change `Coimage` -> `CoimageObject`? Otherwise, I can prepare for this switch and do the renaming here accordingly. In any case, I want this code to be part of `CAP` in the future (This package is my playground for features I need without delay).

2022-03-28 08:25 UTC, zickgraf commented
Thanks for the thorough explanation @sebastianpos! With this I'm happy with the current names.

@mohamed-barakat I don't see a downside of naming the functorial `CoimageObjectFunctorial`. From grepping through packages it looks like there aren't many occurrences of `Coimage`, so maybe I do the renaming in the near future.

2022-03-28 14:38 UTC, zickgraf requested changes

2022-03-28 14:38 UTC, zickgraf commented on gap/Tools.gd
> +#! @Returns a morphism in $\mathrm{Hom}(\mathrm{Coimage}( \alpha ), \mathrm{Coimage}( \alpha' ))$
```suggestion
#! @Returns a morphism in $\mathrm{Hom}(\mathrm{CoimageObject}( \alpha ), \mathrm{CoimageObject}( \alpha' ))$
```

2022-03-28 14:38 UTC, zickgraf commented on gap/Tools.gd
> +#! and an object $r = \mathrm{Coimage}( \alpha' )$.
```suggestion
#! and an object $r = \mathrm{CoimageObject}( \alpha' )$.
```

2022-03-28 14:38 UTC, zickgraf commented on gap/Tools.gd
> +#! $\mathrm{Coimage}( \alpha ) \rightarrow \mathrm{Coimage}( \alpha' )$
```suggestion
#! $\mathrm{Coimage}( \alpha ) \rightarrow \mathrm{CoimageObject}( \alpha' )$
```

2022-03-31 08:30 UTC, merged